package org.sharad.velvetinvestment.utils.tradingaccount

enum class Country(
    val code: String,
    val displayName: String
) {
    AFGHANISTAN("001", "Afghanistan"),
    ALAND_ISLANDS("002", "Aland Islands"),
    ALBANIA("003", "Albania"),
    ALGERIA("004", "Algeria"),
    AMERICAN_SAMOA("005", "American Samoa"),
    ANDORRA("006", "Andorra"),
    ANGOLA("007", "Angola"),
    ANGUILLA("008", "Anguilla"),
    ANTARCTICA("009", "Antarctica"),
    ANTIGUA_AND_BARBUDA("010", "Antigua And Barbuda"),
    ARGENTINA("011", "Argentina"),
    ARMENIA("012", "Armenia"),
    ARUBA("013", "Aruba"),
    AUSTRALIA("014", "Australia"),
    AUSTRIA("015", "Austria"),
    AZERBAIJAN("016", "Azerbaijan"),
    BAHAMAS("017", "Bahamas"),
    BAHRAIN("018", "Bahrain"),
    BANGLADESH("019", "Bangladesh"),
    BARBADOS("020", "Barbados"),
    BELARUS("021", "Belarus"),
    BELGIUM("022", "Belgium"),
    BELIZE("023", "Belize"),
    BENIN("024", "Benin"),
    BERMUDA("025", "Bermuda"),
    BHUTAN("026", "Bhutan"),
    BOLIVIA("027", "Bolivia"),
    BOSNIA_AND_HERZEGOVINA("028", "Bosnia And Herzegovina"),
    BOTSWANA("029", "Botswana"),
    BOUVET_ISLAND("030", "Bouvet Island"),
    BRAZIL("031", "Brazil"),
    BRITISH_INDIAN_OCEAN_TERRITORY("032", "British Indian Ocean Territory"),
    BRUNEI_DARUSSALAM("033", "Brunei Darussalam"),
    BULGARIA("034", "Bulgaria"),
    BURKINA_FASO("035", "Burkina Faso"),
    BURUNDI("036", "Burundi"),
    CAMBODIA("037", "Cambodia"),
    CAMEROON("038", "Cameroon"),
    CANADA("039", "Canada"),
    CAPE_VERDE("040", "Cape Verde"),
    CAYMAN_ISLANDS("041", "Cayman Islands"),
    CENTRAL_AFRICAN_REPUBLIC("042", "Central African Republic"),
    CHAD("043", "Chad"),
    CHILE("044", "Chile"),
    CHINA("045", "China"),
    CHRISTMAS_ISLAND("046", "Christmas Island"),
    COCOS_KEELING_ISLANDS("047", "Cocos (Keeling) Islands"),
    COLOMBIA("048", "Colombia"),
    COMOROS("049", "Comoros"),
    CONGO("050", "Congo"),
    CONGO_DEMOCRATIC_REPUBLIC("051", "Congo, The Democratic Republic Of The"),
    COOK_ISLANDS("052", "Cook Islands"),
    COSTA_RICA("053", "Costa Rica"),
    COTE_DIVOIRE("054", "Cote DIvoire"),
    CROATIA("055", "Croatia"),
    CUBA("056", "Cuba"),
    CYPRUS("057", "Cyprus"),
    CZECH_REPUBLIC("058", "Czech Republic"),
    DENMARK("059", "Denmark"),
    DJIBOUTI("060", "Djibouti"),
    DOMINICA("061", "Dominica"),
    DOMINICAN_REPUBLIC("062", "Dominican Republic"),
    ECUADOR("063", "Ecuador"),
    EGYPT("064", "Egypt"),
    EL_SALVADOR("065", "El Salvador"),
    EQUATORIAL_GUINEA("066", "Equatorial Guinea"),
    ERITREA("067", "Eritrea"),
    ESTONIA("068", "Estonia"),
    ETHIOPIA("069", "Ethiopia"),
    FALKLAND_ISLANDS("070", "Falkland Islands (Malvinas)"),
    FAROE_ISLANDS("071", "Faroe Islands"),
    FIJI("072", "Fiji"),
    FINLAND("073", "Finland"),
    FRANCE("074", "France"),
    FRENCH_GUIANA("075", "French Guiana"),
    FRENCH_POLYNESIA("076", "French Polynesia"),
    FRENCH_SOUTHERN_TERRITORIES("077", "French Southern Territories"),
    GABON("078", "Gabon"),
    GAMBIA("079", "Gambia"),
    GEORGIA("080", "Georgia"),
    GERMANY("081", "Germany"),
    GHANA("082", "Ghana"),
    GIBRALTAR("083", "Gibraltar"),
    GREECE("084", "Greece"),
    GREENLAND("085", "Greenland"),
    GRENADA("086", "Grenada"),
    GUADELOUPE("087", "Guadeloupe"),
    GUAM("088", "Guam"),
    GUATEMALA("089", "Guatemala"),
    GUERNSEY("090", "Guernsey"),
    GUINEA("091", "Guinea"),
    GUINEA_BISSAU("092", "Guinea-Bissau"),
    GUYANA("093", "Guyana"),
    HAITI("094", "Haiti"),
    HEARD_ISLAND_AND_MCDONALD_ISLANDS("095", "Heard Island And Mcdonald Islands"),
    HOLY_SEE("096", "Holy See (Vatican City State)"),
    HONDURAS("097", "Honduras"),
    HONG_KONG("098", "Hong Kong"),
    HUNGARY("099", "Hungary"),
    ICELAND("100", "Iceland"),
    INDIA("101", "India"),
    INDONESIA("102", "Indonesia"),
    IRAN("103", "Iran, Islamic Republic Of"),
    IRAQ("104", "Iraq"),
    IRELAND("105", "Ireland"),
    ISLE_OF_MAN("106", "Isle Of Man"),
    ISRAEL("107", "Israel"),
    ITALY("108", "Italy"),
    JAMAICA("109", "Jamaica"),
    JAPAN("110", "Japan"),
    JERSEY("111", "Jersey"),
    JORDAN("112", "Jordan"),
    KAZAKHSTAN("113", "Kazakhstan"),
    KENYA("114", "Kenya"),
    KIRIBATI("115", "Kiribati"),
    KOREA_DEMOCRATIC_PEOPLES_REPUBLIC("116", "Korea, Democratic Peoples Republic Of"),
    KOREA_REPUBLIC("117", "Korea, Republic Of"),
    KUWAIT("118", "Kuwait"),
    KYRGYZSTAN("119", "Kyrgyzstan"),
    LAO_PEOPLES_DEMOCRATIC_REPUBLIC("120", "Lao Peoples Democratic Republic"),
    LATVIA("121", "Latvia"),
    LEBANON("122", "Lebanon"),
    LESOTHO("123", "Lesotho"),
    LIBERIA("124", "Liberia"),
    LIBYAN_ARAB_JAMAHIRIYA("125", "Libyan Arab Jamahiriya"),
    LIECHTENSTEIN("126", "Liechtenstein"),
    LITHUANIA("127", "Lithuania"),
    LUXEMBOURG("128", "Luxembourg"),
    MACAO("129", "Macao"),
    MADAGASCAR("131", "Madagascar"),
    MALAWI("132", "Malawi"),
    MALAYSIA("133", "Malaysia"),
    MALDIVES("134", "Maldives"),
    MALI("135", "Mali"),
    MALTA("136", "Malta"),
    MARSHALL_ISLANDS("137", "Marshall Islands"),
    MARTINIQUE("138", "Martinique"),
    MAURITANIA("139", "Mauritania"),
    MAURITIUS("140", "Mauritius"),
    MAYOTTE("141", "Mayotte"),
    MEXICO("142", "Mexico"),
    MICRONESIA("143", "Micronesia, Federated States Of"),
    MOLDOVA("144", "Moldova, Republic Of"),
    MONACO("145", "Monaco"),
    MONGOLIA("146", "Mongolia"),
    MONTSERRAT("147", "Montserrat"),
    MOROCCO("148", "Morocco"),
    MOZAMBIQUE("149", "Mozambique"),
    MYANMAR("150", "Myanmar"),
    NAMIBIA("151", "Namibia"),
    NAURU("152", "Nauru"),
    NEPAL("153", "Nepal"),
    NETHERLANDS("154", "Netherlands"),
    NETHERLANDS_ANTILLES("155", "Netherlands Antilles"),
    NEW_CALEDONIA("156", "New Caledonia"),
    NEW_ZEALAND("157", "New Zealand"),
    NICARAGUA("158", "Nicaragua"),
    NIGER("159", "Niger"),
    NIGERIA("160", "Nigeria");
    companion object {
        fun fromCode(code: String?): Country? {
            return entries.firstOrNull { it.code == code }
        }
        fun getDisplayNameFromCode(code: String?): String? {
            return fromCode(code)?.displayName
        }
    }
}